### ISSUE TITLE
No problem at all - Just saying this works great!

### ISSUE THREAD

**Issue by lucwuyts** [davglass/doorbot#11]
Thanks for your library. 
This is working great !!

I now use it to query the battery status, sent it to my mqtt server, and from there node-red starts mailing me every 1% under 10% capacity.
(for some reason I don't receive the battery status messages from ring)

Regards,
Luc

**Comment by mrose17** [comment]
+1

**Comment by davglass** [comment]
@lucwuyts Thanks! That's awesome, to be honest that's the exact reason I wrote this library! I needed a way to add this battery-check to my Nagios setup :)
