### ISSUE TITLE
Retrieve *all* videos?

### ISSUE THREAD

**Issue by mvanio** [davglass/doorbot#12]
Currently using this I only seem to be able to get 20 or so mp4s. I'd like to download the entire history. Is that possible?

Works fine otherwise - great work!

**Comment by davglass** [comment]
I don't know if there is a way to get more than the latest from their API. I would need to look into the queries to see what params to send, the API doesn't return any useful info on how to get more items.

**Comment by kolecke** [comment]
adding an obnoxiously large **limit** query parameter to the history call would allow you to get all available history and then download all known videos (i.e., d.query.limit=Number.MAX_SAFE_INTEGER on line 59).

**Comment by davglass** [comment]
I just pushed up `doorbot@3.1.0` with support for `doorbot.history(limit, callback)` which will let you pick the number of items to return.

**Comment by wackyvac** [comment]
@davglass @kolecke  Struggling to get this to download more than 2 recent days worth when I have 60 days history. I'm getting a return like: Done, Oldest File: 1e+21.  I'm using the download-all.js and upped the limit and the 'parseInt' number. Desperate to get this working as I am moving my system and once I cancel the monitoring I lose all videos.
