### ISSUE TITLE
Question about health checks

### ISSUE THREAD

**Issue by sunbit** [davglass/doorbot#14]
Hello,

I see in one of the issues that you use this code to monitor battery status, and that's exactly what i wanted to do. As for your experience with this, do you know: 
- how often is the device is checked for health?
- is there any way to force a read to update battery status?
- i can't see the "last health check" date that is show on the app, in the api responses, do you know if that is available?

Thank you very much

**Comment by davglass** [comment]
I don't know the timing they use for that. I added mine to my Nagios checks to check for battery and wifi status. I'm not sure if the API returns it immediately or if it's cached on their end. I do know it's pretty accurate as I can see the same data in the app that I see on the API.
