### ISSUE TITLE
Limit of 100?

### ISSUE THREAD

**Issue by gristie** [davglass/doorbot#21]
I seem unable to get more than 100 entries returned from history, setting any number over 100 seems to just return 100 - the same applies using the example downloader.  Is this a limitation of the ring api?

Thanks

**Comment by davglass** [comment]
I believe that it is, I have never been able to get more than that from the api.

**Comment by lmoga** [comment]
The API will only return 100 items at a time, however, you can specify you want items "older than" a particular recording, thus getting all your videos by changing the older_than value to the oldest video you have, then running the command again.

In the doorbot.js script, like 303, change it to this:

const url = `/doorbots/history?older_than={ID_OF_OLDEST_VIDEO_YOU_HAVE_HERE}&limit=${limit}`

Example: const url = `/doorbots/history?older_than=6578465727216031363&limit=${limit}`

If you get 100 videos, and the oldest video (lowest ID number) is 6578465727216031363, then changing line 303 to the above would get you the 100 NEXT OLDEST videos.  Once you have those 100, change the ID to the new oldest video and repeat.  If no one makes doorbot.js do this automatically, I'll attempt to figure out Node and post a pull request, I've just been manually changing the value in doorbots.js myself, for the time being.

**Comment by davglass** [comment]
Published this in `doorbot@5.2.0`

`ring.history(limit, older_than, callback) => (error, array)` - `limit` - The `Number` of items to return from the history. `older_than` - The ID of the latest history item to start with when going backward.
