### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by Doudy** [davglass/doorbot#22]
Hello,
I would like to be able to test this program.
I have no idea how to do it.  
How to compile them?
I am very very beginner.

**Comment by joeyberkovitz** [comment]
Just run `npm install doorbot` then you can use the examples in the readme

**Comment by itsgabraf** [comment]
Am I the only one who still doesn't know how to run this?? Installed then lost as in what to do. Cant be that hard to write up a quick an easy how-to for us less advanced users

**Comment by lucwuyts** [comment]
This was my setup:
Installation:  
make a folder c:\scripts
Open a command prompt and    cd c:\scripts
Install the needed modules:
- ring api    -> npm i doorbot --save
- mqtt client -> npm i mqtt --save
- async -> npm i async --save
(i don't remember if this is complete)
(I use the Mqtt client to send the battery status and health to an Mqtt server.)

This installed all node modules in the folder   c:\scripts\node_modules
In the folder scripts: i have a javascript file   "deurbel.js"

Content of this script:

`
const RingAPI = require('doorbot');
const mqtt = require('mqtt');
const async = require('async');


const ring = RingAPI({
    email: 'xxxxxxx@xxxx.xxx',
    password: 'xxxxxxx'    
});


var client = mqtt.connect({ host:'automation' , port: 1883, username: "xxxxx" , password: "xxxxxx" })
client.on('connect' , function() {
		console.log("connected to MQTT")
	})
	client.on('error' , function(e) { console.log( e ) } )
	

//ring.history(( e , history ) => { console.log(e, history); })


ring.devices((e,devices) => {

	console.log(e,"Token: "+ring.token )		
    	var doorbots = devices["doorbots"];    		
	console.log(devices);
	var mijnbel = doorbots[0];
	// console.log(mijnbel)
	var batt = mijnbel["battery_life"]
	console.log( batt );
	client.publish('ring/battery' , batt , {qos: 2, retain: true } )		

		
	ring.health(mijnbel,(e,h) => { 
		console.log(h) 
		var json = JSON.stringify(h);
		
		client.publish('ring/health/ring' , json , {qos: 2, retain: true } )		
		
		client.end()
	});
})`

Execute this script:
"C:\Program Files\nodejs\node.exe"   c:\scripts\deurbel.js

**Comment by itsgabraf** [comment]
I get this error

TypeError: RingAPI is not a function
    at Object.<anonymous> (/usr/lib/node_modules/doorbot/doorbot.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**Comment by lucwuyts** [comment]
Is your doorbot.js file maybe damaged?
The first error is on line 3 ?? 
If you look at the source of this file, there is no mention of a RingApi function at that line

https://github.com/davglass/doorbot/blob/master/doorbot.js

**Comment by itsgabraf** [comment]
Got it! I accidentally added the script from the API into the doorbot.js, all fixed now once I properly created a seperate .js - question though, now that this is all working, is there a way to pull a URL to use for adding the Ring doorbell to Homebridge?

**Comment by itsgabraf** [comment]
Question, after it lists the latest recorded videos, I see a long link which when I click it, it goes to the latest recording. Is this link going to change once a new recording is added, or is it a URL for the latest recording (and won't change so I can bookmark it and always see the latest video?)

**Comment by joeyberkovitz** [comment]
Not sure which endpoint you're using, but you can request the history and then from that id get the recording URL

**Comment by Doudy** [comment]
Another question of beginner
It's for Windows or Linux?

**Comment by lucwuyts** [comment]
I work with windows, but node.js (and javascript) is also working on Linux.
