### ISSUE TITLE
API Version 11

### ISSUE THREAD

**Issue by joeyberkovitz** [davglass/doorbot#24]
It looks like the app is now using API version 11. I'm not sure if using the app causes Ring to force you onto the latest version, but the account that I used with the latest version of the app no longer works with this and an account that isn't used works normally.

**Comment by davglass** [comment]
That's interesting, I am in the beta group and have the beta app and my account still works..

**Comment by davglass** [comment]
Just pushed up `doorbot@5.1.0`, you can now add `api_version: 11` to the `constructor` and have it use that when making calls. I used both `9` and `11` to test and it worked for my tests.
