### ISSUE TITLE
Is intercepting ring's https via mitmproxy in transparent mode still possible 

### ISSUE THREAD

**Issue by jimhigson** [davglass/doorbot#28]
Hi,

My setup for intercepting ring traffic has stopped working recently, even though it works for other https websites. It looks like the ring app might not be trusting the MITMproxy CA any more, even though the rest of the OS does trust it.

Do still you have a technique that works to intercept traffic, and if so, would it be possible to document the steps perhaps in the repo?

![screenshot at aug 03 19-42-35](https://user-images.githubusercontent.com/136306/43659996-970f95c4-9755-11e8-98a0-872458daf627.png)

Worried 3rd party APIs are getting more and more difficult to make for these devices.

**Comment by TheOriginalMrWolf** [comment]
Is there a substantial difference between how ring-api and doorbot authenticate, as doorbot still works?

**Comment by jimhigson** [comment]
From looking at the source they are almost identical, but it is possible
there is a subtle difference

**Comment by mrose17** [comment]
short answer: "no".

ring's applications all use pinned certificates, to MITM proxying is no longer feasible.
