### ISSUE TITLE
homebridge plugin for ring video doorbell

### ISSUE THREAD

**Issue by mrose17** [davglass/doorbot#3]
hi. i'm the author of https://github.com/homespun/homebridge-platform-ring-video-doorbell ...

i wish i had started a month later on that plugin for homebridge (homekit for the impatient), cause then i wouldn't have had to transcode the PHP API from https://github.com/jeroenmoors -- https://github.com/jeroenmoors/php-ring-api -- there's nothing wrong with his API, of course, it just would have been faster to use yours.

anyone my gameplan is to move over to your API and see if i get better results...

many thanks!

**Comment by davglass** [comment]
Awesome! Let me know if I can help or feel free to send along any PR's that make this module easier to use.

**Comment by mrose17** [comment]
will do, thanks!
