### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by broyuken** [davglass/doorbot#38]
Hi,

Looking through this, it all looks great but what is the actual use case on this? Like how are people actually using this? Do you have a web page that kicks off these scripts, do they tie in with openHAB or SmartThings, etc. or are you just running these from a command line when you want to get info?

**Comment by yepher** [comment]
My use-case is to pull the videos and extract faces as images from videos and then email a daily digest of "who" was at my door. 

I am also making a daily digest web view that shows just an image of what the major difference is in each video is. That makes it super easy to see what happened without needing to physically watch the videos.

I would ideally like to be able to get the live stream as soon as it is triggered and show who is at my door without the need to play the videos. But I've not tried that yet. Still sorting out bugs in the first use-cases.
