### ISSUE TITLE
Get device IDs for all the devices

### ISSUE THREAD

**Issue by icucTrader** [davglass/doorbot#39]
Would it be possible to get the Device IDs for the devices in the account? I'm trying to setup the Smartthings to turn on the Siren based on the motion at late night. 

I have a Ring pro and 2 floodlights. I was able to get the device ID using the postman but just got only one device ID. I don’t know if the device ID is for the floodlight or doorbell.

The siren and spotlight are not working for me. It could be the device id that was causing the problem.

**Comment by davglass** [comment]
Calling `ring.devices()` should return an array of all the devies bound to your account. Each item in the array should contain the device id for them.

**Comment by icucTrader** [comment]
Thanks and i was following the instructions from the below link. He has taken your example and developed the Json file. There is a method to retrieve the device details but it returns nothing when I send the get devices request. 

https://philipnye.com/2017/12/29/control-your-ring-spotlight-with-alexa-with-smart-things/

I'm not an expert but any help would be appreciated.

**Comment by icucTrader** [comment]
I was able to resolve this using the postman. Thanks everyone,
