### ISSUE TITLE
How can I download all of my videos on ring.com

### ISSUE THREAD

**Issue by guestuser6** [davglass/doorbot#4]
My video files is going to be deleted off ring.com as its 6 months old. 
Would you be able to show me a script that can download all of my videos on ring.com ?
I am on a linux machine.

Thanks for your consideration

**Comment by davglass** [comment]
It's not too hard if you have node installed:

* npm install async doorbot

```js
const ring = require('doorbot');
const async = require('async');

const email = 'your@email.com';
const password = 'password';

ring.authenticate(email, password, (e, token) => {
        ring.history(token, (e, history) => {
            const fetch = (info, callback) => {
                ring.recording(token, info.id, (e, recording) => {
                    console.log(recording);
                    callback();
                });
            };


            async.eachLimit(history, 10, fetch, () => {
                console.log('done');
            });
        });
});
```

That will print a list of the URL's to the video files. You can use whatever means needed to download the videos from these URL's.

**Comment by foocheung** [comment]
Thanks Dave, sorry I am not familar with running this code, can you point me to a url to show me how to run this in a linux box.

Thanks again
